os: linux
dist: trusty
sudo: required

language: node_js
node_js:
  - "13.2.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
    - /.*/

install:
  - npm install -g @angular/cli
  - npm install

jobs:
  include:
    ## Build Stage  ##
    - stage: Build App
      if: branch = master
      script:
      - ng --version
      - ng build



notifications:
  email:
    on_failure: never
    on_success: never
