os: linux
dist: trusty
sudo: required

language: node_js
node_js:
  - "13"

branches:
  only:
    - master, development

install:
  - npm install -g @angular/cli
  - npm install

jobs:
  include:
    ## Build Stage  ##
    - stage: Build App
      if: branch = master
      script:
      - ng build --prod



notifications:
  email:
    on_failure: never
    on_success: never
