os: linux
dist: trusty
sudo: required

language: node_js
node_js:
  - "12"
  - "14"

branches:
  only:
    - master

install:
  - npm install

jobs:
  include:
    ## Build Stage  ##
    - stage: Build App
      script:
      - ng build --prod

notifications:
  email:
    on_failure: never
    on_success: never
